trigger:
  branches:
    include:
      - main

stages:
  - stage: windows_latest
    displayName: 'windows-latest'
    dependsOn: [ ]
    pool:
      vmImage: 'windows-latest'
    jobs:
      - job: CreatePackage
        displayName: 'CreatePackage'
        dependsOn: [ ]
        steps:
          - task: CmdLine@2
            inputs:
              script: './build/build.cmd'
          - task: PublishBuildArtifacts@1
            inputs:
              artifactName: Nice3point.Revit.Solution
              pathtoPublish: 'output'
