name: Compile solution

on:
  push:
    branches:
      - '*'
  pull_request:

jobs:
  windows:
    name: windows-2025
    runs-on: windows-2025
    steps:

      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Cache packages
        uses: actions/cache@v5
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj', 'Directory.Build.props', 'Directory.Packages.props') }}
          restore-keys: ${{ runner.os }}-nuget-

      - name: Compile solution
        run: dotnet run -c Release
        working-directory: "build"
        env:
          DOTNET_ENVIRONMENT: ${{ github.ref_name == 'main' && 'Production' || 'Development' }}