name: Publish Release

on:
  push:
    tags:
      - '*'

jobs:
  windows:
    name: windows-2025
    runs-on: windows-2025
    steps:

      - name: Checkout
        uses: actions/checkout@v6

      - name: Cache NuGet
        uses: actions/cache@v5
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj', 'Directory.Build.props', 'Directory.Packages.props') }}
          restore-keys: ${{ runner.os }}-nuget-

      - name: Publish packages
        run: dotnet run -c Release -- pack publish
        working-directory: "build"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOTNET_ENVIRONMENT: ${{ (github.ref_name == 'main' || github.ref_type == 'tag') && 'Production' || 'Development' }}
          Publish__Version: ${{ github.ref_name }}
          NuGet__ApiKey: ${{ secrets.NUGET_API_KEY }}